version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER:-kursorganizer}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-example}
      - POSTGRES_DB=${DB_NAME:-stands}


